//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoreTechs_CodeTest_10_24_2016.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    public partial class Car
    {
        public int id { get; set; }
        [MaxLength(50, ErrorMessage = "Car Make cannot exceed 50 characters")]
        public string make { get; set; }
        [MaxLength(50, ErrorMessage = "Car Model cannot exceed 50 characters")]
        public string model_name { get; set; }
        [MaxLength(128, ErrorMessage = "Car Trim cannot exceed 128 digits")]
        public string model_trim { get; set; }
        [MaxLength(4, ErrorMessage = "Car Year cannot exceed 4 digits")]
        public string model_year { get; set; }
        public string body_style { get; set; }
        public string engine_position { get; set; }
        public string engine_cc { get; set; }
        public string engine_num_cyl { get; set; }
        public string engine_type { get; set; }
        public string engine_valves_per_cyl { get; set; }
        public string engine_power_ps { get; set; }
        public string engine_power_rpm { get; set; }
        public string engine_torque_nm { get; set; }
        public string engine_torque_rpm { get; set; }
        public string engine_bore_mm { get; set; }
        public string engine_stroke_mm { get; set; }
        public string engine_compression { get; set; }
        public string engine_fuel { get; set; }
        public string top_speed_kph { get; set; }
        public string zero_to_100_kph { get; set; }
        public string drive_type { get; set; }
        public string transmission_type { get; set; }
        public string seats { get; set; }
        public string doors { get; set; }
        public string weight_kg { get; set; }
        public string length_mm { get; set; }
        public string width_mm { get; set; }
        public string height_mm { get; set; }
        public string wheelbase { get; set; }
        public string lkm_hwy { get; set; }
        public string lkm_mixed { get; set; }
        public string lkm_city { get; set; }
        public string fuel_capacity_l { get; set; }
        public string sold_in_us { get; set; }
        public string co2 { get; set; }
        public string make_display { get; set; }
    }
}
